# Generated by Django 6.1 on 2026-08-24 19:40

from django.db import migrations

def populate_test_quiz_data(apps, schema_editor):
    Course = apps.get_model("assignment_portal", "Course")
    Question = apps.get_model("assignment_portal", "Question")
    Answer = apps.get_model("assignment_portal", "Answer")

    # Course 1 quiz
    sql = Course.objects.create(name="Basics of SQL")

    question = Question.objects.create(
        course = sql,
        text = "SQL injection is not a serious security flaw."
    )

    answer = Answer.objects.create(
        question = question,
        text = "True",
        is_correct = False
    )

    answer = Answer.objects.create(
        question = question,
        text = "False",
        is_correct = True
    )

    question = Question.objects.create(
        course = sql,
        text = "SQL stands for Super Quick Language"
    )

    answer = Answer.objects.create(
        question = question,
        text = "True",
        is_correct = False
    )   

    answer = Answer.objects.create(
        question = question,
        text = "False",
        is_correct = True
    )

    # Course 2 quiz

    python = Course.objects.create(name="Python 101")

    question = Question.objects.create(
        course = python,
        text = "Python is a high-level language."
    )

    answer = Answer.objects.create(
        question = question,
        text = "True",
        is_correct = True
    )

    answer = Answer.objects.create(
        question = question,
        text = "False",
        is_correct = False
    )

    question = Question.objects.create(
        course = python,
        text = "Function is defined by keyword \"func\" in python"
    )

    answer = Answer.objects.create(
        question = question,
        text = "True",
        is_correct = False
    )

    answer = Answer.objects.create(
        question = question,
        text = "False",
        is_correct = True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_portal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_test_quiz_data)
    ]
